[package]
name = "snape2"
version = "0.1.0"
edition = "2024"

[dependencies]
turbo = { version = "^3.0.0", package = "turbo-genesis-sdk" }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
