[package]
name = "jumpy"
version = "0.1.0"
edition = "2024"

[package.metadata.turbo]
user = "52d057f0-6b0c-4902-a2ab-3ee2a8de7e40"

[dependencies]
turbo = { version = "5.2.0", package = "turbo-genesis-sdk"}

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
